#' Add phantom knots for B-splines
#'
#' @param x Predictor variable vector.
#' @param knots The innerknots and boundary knots that define the spline. The knots can all be innerknots.
#'
#' @return The knots used to construct the B-splines, including innerknots, boundary knots and phantom knots
#' @export
bs_knots<-function(x,real_knots)
{
  highknot = max(x)
  lowknot = min(x)
  knots <- unique (sort (knots))
  knots <-c(rep(lowknot-0.0001, order), knots, rep(highknot+0.0001, order))
  return(knots)
}
#' Generate an evaluated basis matrix for B-splines
#'
#' @param x Predictor variable vector.
#' @param knots Knots location in terms of quantiles of x_train, optional, default will be evenly
#' spaced quantiles based on number of knots.
#'
#' @return Basis matrix evaluated at each x value.
#' @examples
#' x<-seq(0, 1, 0.001)
#' knots <- seq(0, 1, 0.1)
#'
#' basis<-ncs_basis(x,knots)
#' plot(x,rep(0,length(x)),type="l",ylim=c(0,1))
#' for (i in 1: (length(knots))){
#'   lines(x,basis[,i])
#' }
#' @export
bs_basis <-function (x,order,knots)
{
  j <- length (knots)-2*order # j+order basis functions
  n <- length (x)
  G <- matrix (0,  nrow=n,ncol=(j+2*order-1)) # matrix G is n*(J+q) dimensional, used for coefficient estimation.
  for (i in 1: (j+2*order-1)){
    G[,i]<-ifelse((x>=knots[i]&x<knots[i+1]),1,0)
  }
  for (k in 2:order){
    N<-G
    for (i in 1: (j+2*order-k)){
      if((knots[i+(k-1)]-knots[i])==0&&(knots[i+k]-knots[i+1])==0){
        G[,i]<-rep(0,n)
      }else if ((knots[i+(k-1)]-knots[i])==0){
        G[,i]<-(knots[i+k]-x)/(knots[i+k]-knots[i+1])*N[,(i+1)]
      }else if ((knots[i+k]-knots[i+1])==0){
        G[,i]<-(x-knots[i])/(knots[i+(k-1)]-knots[i])*N[,i]
      }else{
        G[,i]<-(x-knots[i])/(knots[i+(k-1)]-knots[i])*N[,i]+(knots[i+k]-x)/(knots[i+k]-knots[i+1])*N[,(i+1)]
      }
    }
  }
  return (G[,1:(j+order)])
}


#' Generating B-spline basis
#'
#' This function generates B-spline basis. The B-splines are defined following
#' the recursive formulas due to de Boor. Only univariate input can be used.
#'
#' @param x The input vector of training dataset.
#' @param y The output vector of training dataset.
#' @param order The order of B-spline functions. The default is order=4 for cubic B-splines.
#' @param knots The innerknots and boundary knots that define the spline.
#' @return A list with the following components:
#' \item{beta}{ The coefficients of nonparametric regression.}
#' \item{basis}{The B-spline basis matrix of dimension c(length(x), df). df = length(innerknots) + order.}
#' \item{knots}{The knots used to construct the B-splines, including innerknots, boundary knots and phantom knots}
#' \item{order}{The order of basis functions. order=degree+1}
#' @examples
#' x<-seq(0, 1, 0.001)
#' y <- x^3 * 3 - x^2 * 2 + x + exp(1)+rnorm(length(x),0,0.1)
#' plot(x,y)
#' knots <- seq(0, 1, 0.1)
#' order<-4
#'
#' basis<-bs_train(x,y,order,knots)
#' plot(x,rep(0,length(x)),type="l",ylim=c(0,1))
#' for (i in 1: (length(knots)+order)){
#'   lines(x,basis$basismatrix[,i])
#' }
#' @export
bs_train <-function (x,y,order,real_knots) #degree<-order-1
{
  knots<-bs_knots(x,real_knots)
  G<-bs_basis(x,order,knots)
  beta<-(MASS::ginv(t(G)%*%G))%*%t(G)%*%y
  solution<-list("beta"=beta ,"basismatrix" = G,"knots"=knots, "order"=order)
  return (solution)
}
#' Prediction using regression spline with B-spline basis
#'
#' This function provides prediction at value of interest using regression spline with B-spline basis. The B-splines are generated by the function \code{bs_train}.
#' The return value of \code{bs_train} is required as an argument of \code{bs_predict}
#'
#' @param x_test The input values at which evaluations are required.
#' @param basis The return value of function \code{bs_train}.
#' @return The evaluated output at x_test.
#' @examples
#' x<-seq(0, 1, 0.001)
#' y <- x^3 * 3 - x^2 * 2 + x + exp(1)+rnorm(length(x),0,0.1)
#' plot(x,y)
#' knots <- seq(0.1, 0.9, 0.01)
#' order<-4

#' basis<-bs_train(x,y,order,knots)
#'
#' x_test<-seq(0, 1, 0.01)
#' fit<-bs_predict(x_test,basis)

#' plot(x_test,fit)
#' lines(x_test,x_test^3 * 3 - x_test^2 * 2 + x_test + exp(1),col="red")
#' @export
bs_predict<-function (x_test,order=NULL,knots=NULL,beta=NULL,basis=NULL) #knots should contain phantom knots or generated from bs_knots
{
  if(is.null(basis)==0) #basis is not null
  {
    knots<-basis$knots
    order<-basis$order
    beta<-basis$beta
  }
  if(is.null(basis)&(is.null(order)|is.null(knots)|is.null(beta))) #basis is null and some parameters are null
  {
    print("some necessary parameters (order/knots/beta) are missing!")
  }
  basis<-bs_basis(x_test,order,knots)
  f<-phi_b%*%beta
  return (f)
}


